/*
** detect_visualizer.c for OCR in src/recognition
**
** Made by SheatNoisette
** Login   SheatNoisette
**
** Started on  2019 SheatNoisette
*/
/*  Visualize data on image */

#include <stdlib.h>
#include <stdio.h>

#include "../bitmap/image.h"
#include "../bitmap/image_drawing.h"
#include "../commons/linked_list.h"

/*
** Draw border box of the entire image
** Take an image type and the output of r_get_paragraph_border
*/

void visu_draw_border_box (image *input, int *border_box, 
unsigned char r, unsigned char g, unsigned char b) {
    /* Draw the border box rectangle */
    image_draw_rectangle(input, 
        *(border_box),     /* x1 */
        *(border_box + 1), /* y1 */
        *(border_box + 2), /* x2 */
        *(border_box + 3), /* y2*/
        r, g, b);
}

/*
** Draw the y positions of the characters using r_find_char_y output and border
** Box
*/

void visu_draw_y_char_pos (image *input, l_list *y_positions, int *border_box,
unsigned char r, unsigned g, unsigned char b) {

    /* Iterator */
    unsigned long y;

    /* Get list length */
    unsigned long l_length = list_length(y_positions);

    /* Check if the list exists or contains data */
    if (l_length == 0) {
        return;
    }

    /* Draw horizontal lines - minmum border to max border */
    for (y = 0; y < l_length; y++) {
        image_draw_line_h(input, *(border_box), *(border_box + 2), 
        list_get_value(y_positions, y), r, g, b);
    } 
}

/*
** Draw a rectangle which outlines the caracters
** image - list of char generated by r_find_char_image
*/

void visu_draw_border_letter(image *input, l_list *char_list,
unsigned char r, unsigned char g, unsigned char b) {

    /* Iterator */
    unsigned long i;

    for (i = 0; i < list_length(char_list); i+=4) {
        image_draw_rectangle(input,
        list_get_value(char_list, i),
        list_get_value(char_list, i + 1),
        list_get_value(char_list, i + 2),
        list_get_value(char_list, i + 3),
        r, g, b);
    }
}

/*
** Visualisation of the text_structure() output in terminal
** 
*/
void visu_text_structure(l_list *t_structure) {

    /* Iterator */
    unsigned long cursor;

    /* Get length of the list */
    unsigned long list_size = list_length(t_structure);

    /* Allocate memory for string */
    char *out_string = (char *)malloc(list_size * sizeof(char) + 1);
    
    /* Check malloc */
    if (out_string == NULL) {
        printf("[Visual] Failed to allocate memory for text structure");
        return;
    }

    /* Build string visualization */
    for (cursor = 0; cursor < list_size; cursor++) {
        
        /* Space */
        if (list_get_value(t_structure, cursor) == 0)
            *(out_string + cursor) = ' ';
        /* Letter */
        else if (list_get_value(t_structure, cursor) == 1)
            *(out_string + cursor) = 'x';
        else
            /* Return */
            *(out_string + cursor) = '\n';
    }

    /* Close string */
    *(out_string + list_size) = '\0';

    /*  Print to terminal */
    printf("=== Text structure ===\n%s\n", out_string);

    /* Free string */
    free(out_string);
}